language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

services:
  - memcached

before_install:
  - phpenv config-add tests/travis.ini

install:
  - composer require satooshi/php-coveralls --no-interaction

script:
  - phpunit --verbose --stderr --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  webhooks:
    - http://build.miaoxingyun.com/travis-notifications
